#data preparation
source("./R/subscripts/modern_environmental_data.R")
rm(list = ls())
source("./R/subscripts/palaeoenvironmental_data.R")
rm(list = ls())
source("./R/subscripts/prepare_ReefBase_data.R")
rm(list = ls())

#run maxent
system("./maxent/maxent.sh")

#post-modelling analyses
source("./R/subscripts/prepare_fossil_reef_data.R")
rm(list = ls())
source("./R/subscripts/binary_conversion.R")
rm(list = ls())
source("./R/subscripts/centroid_calc.R")
rm(list = ls())
source("./R/subscripts/reef_zone_calc.R")
rm(list = ls())
source("./R/subscripts/area_calc.R")
rm(list = ls())
source("./R/subscripts/calculate_boyce.R")
rm(list = ls())
source("./R/subscripts/model_performance.R")
rm(list = ls())
source("./R/subscripts/model_performance_cont.R")
rm(list = ls())
source("./R/subscripts/lat_variables.R")
rm(list = ls())

#figures
source("./R/figures/centroid_plot.R")
rm(list = ls())
source("./R/figures/habitat_area_global.R")
rm(list = ls())
source("./R/figures/habitat_area_lat.R")
rm(list = ls())
source("./R/figures/performance_plot.R")
rm(list = ls())
source("./R/figures/reef_distribution.R")
rm(list = ls())
source("./R/figures/reef_zone.R")
rm(list = ls())
source("./R/figures/rotation_plot.R")
rm(list = ls())
source("./R/figures/variable_plot.R")
rm(list = ls())
source("./R/figures/hab_plots.R")
rm(list = ls())