#data preparation
source("./R/subscripts/extract_reef_data.R")
rm(list = ls())
source("./R/subscripts/modern_environmental_data.R")
rm(list = ls())
source("./R/subscripts/palaeoenvironmental_data.R")
rm(list = ls())
source("./R/subscripts/data_prep.R")
rm(list = ls())

#post-modelling analyses
source("./R/subscripts/binary_conversion.R")
rm(list = ls())
source("./R/subscripts/centroid_calc.R")
rm(list = ls())
source("./R/subscripts/reef_zone_calc.R")
rm(list = ls())
source("./R/subscripts/area_calc.R")
rm(list = ls())
source("./R/subscripts/model_performance.R")
rm(list = ls())

#post-modelling analyses clamped
source("./R/subscripts/clamp_predictions.R")
rm(list = ls())
source("./R/subscripts/centroid_calc_clamp.R")
rm(list = ls())
source("./R/subscripts/reef_zone_calc_clamp.R")
rm(list = ls())
source("./R/subscripts/area_calc_clamped.R")
rm(list = ls())
source("./R/subscripts/model_performance_clamp.R")
rm(list = ls())

#figures
source("./R/figures/centroid_plot.R")
rm(list = ls())
source("./R/figures/habitat_area_global.R")
rm(list = ls())
source("./R/figures/habitat_area_lat.R")
rm(list = ls())
source("./R/figures/performance_plot.R")
rm(list = ls())
source("./R/figures/reef_distribution.R")
rm(list = ls())
source("./R/figures/reef_zone.R")
rm(list = ls())
source("./R/figures/hab_plot_single.R")
rm(list = ls())
